# Generated by Django 4.0.6 on 2022-09-22 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_profile_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tweet',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='post',
            new_name='tweet',
        ),
    ]
