# Generated by Django 4.0.6 on 2022-09-23 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0003_rename_post_tweet_rename_post_comment_tweet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='mention',
            field=models.ManyToManyField(blank=True, related_name='tweet_mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply_mode',
            field=models.CharField(choices=[('everyone', 'everyone'), ('following', 'following'), ('mentioned', 'mentioned')], default='everyone', max_length=10),
        ),
    ]
