# Generated by Django 4.0.6 on 2022-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_tweet_mention_tweet_reply_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='reply_mode',
            field=models.CharField(choices=[('everyone', 'Everyone can reply'), ('following', 'People you follow'), ('mentioned', 'Only people you mention')], default='everyone', max_length=10),
        ),
    ]
