# Generated by Django 4.1.1 on 2022-09-27 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0004_alter_tweet_options_tweet_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='mention',
            new_name='mentions',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='shares',
            field=models.ManyToManyField(related_name='posts_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
