# Generated by Django 4.0.6 on 2022-09-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_tweet_reply_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='filetype',
        ),
        migrations.AddField(
            model_name='media',
            name='extension',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
