# Generated by Django 4.0.6 on 2022-09-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_remove_media_filetype_media_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='extension',
        ),
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
